export class ExterInfoEntity {
  id: string = "";
  create: boolean = false;
  version: number = 0; //版本号
  createBy: string = "";
  createTime: string = "";
  updateBy: string = "";
  updateTime: string = "";
  number: string = ""; //编号
  reportId: string = ""; //举报信息id
  userId: string = ""; //提报人
  facilityId: string = ""; //电力设施id
  discoverDate: string = ""; //发现日期
  cityId: string = ""; //	行政位置
  adminAddr: string = ""; //行政位置详细
  isVip: number = 0; //是否重要用户
  vipType: string = ""; //重要用户类型
  vipName: string = ""; //重要客户名称
  licenses: number = 0; //作业许可
  exterType: string = ""; //外破类型
  exterLevel: number = 0; //外破等级
  lastDate: string = ""; //上一次巡视日期
  siteSituation: string = ""; //现场情况简述
  siteRemark: string = ""; //现场情况备注
  siteRemarkWork: string = ""; //现场情况备注（工作台）
  sitePhone: string = ""; //现场联系电话
  sitePhoto: string = ""; //现场照片
  hiddenTroubleFile: string = ""; //隐患告知书附件
  accidentOrg: string = ""; //肇事单位
  accidentPhone: string = ""; //肇事联系电话
  ownerName: string = ""; //业主
  ownerPhone: string = ""; //业主联系方式
  ownerType: string = ""; //业主类型
  ownerOrg: string = ""; //业主单位
  horizontal: string = ""; //水平距离
  vertical: string = ""; //垂直距离
  treeQuantity: string = ""; //	树木棵树
  constructionFile: string = ""; //施工外破隐患告知书
  constructionOrg: string = ""; //施工单位
  constructionPhone: string = ""; //施工单位联系电话
  powerCut: number = 0; //是否停电
  powerLoss: string = ""; //电量损失
  fiveIsAccept: number = 0; //是否受理
  fiveReason: string = ""; //不受理原因
  fiveHandleOpinion: string = ""; //初步处置意见
  fiveHandleTime: string = ""; //计划处置时间
  sixIsAgree: number = 0; //同意/不同意
  sixOpinion: string = ""; //不同意意见
  sevenDisposeTime: string = ""; //处置时间
  sevenDisposeSituation: string = ""; //处置情况
  sevenSitePhoto: string = ""; //现场照片
  sevenIsAdvice: number = 0; //发放整改通知书
  sevenAdviceTime: string = ""; //	整改通知书发放时间
  sevenAdviceFile: string = ""; //整改通知书附件
  sevenDisposeWay: number = 0; //处置方式
  sevenOliceIsAccept: string = ""; //公安机关是否受理
  sevenPoliceIsTransfer: number = 0; //移交公安机关
  sevenJbajdjb: string = ""; //举报案件登记表
  sevenXcjcjl: string = ""; //现场检查记录
  sevenXzcflaspb: string = ""; //行政处罚立案审批表
  sevenJsdctzs: string = ""; //接受调查通知书
  sevenXcjcjlky: string = ""; //现场检查勘验记录
  sevenDcbl: string = ""; //调查笔录
  sevenAjdczjbg: string = ""; //案件调查终结报告
  sevenWssdhz: string = ""; //文书送达回证
  sevenXzcfgzs: string = ""; //行政处罚告知书
  sevenXzcfjds: string = ""; //行政处罚决定书
  sevenWssdhzxzcfjds: string = ""; //文书送达回证行政处罚决定书
  sevenZxqkjl: string = ""; //执行情况记录
  sevenXzcfajjabg: string = ""; //行政处罚案件报告
  sevenAjysspb: string = ""; //案件移送审批表
  sevenAjysh: string = ""; //案件移送函
  sevenGafh: string = ""; //公安复函
  sevenFile: string = ""; //其它附件
  sevenAllFolder: string = ""; //全卷宗
  sevenPunishWay: number = 0; //处罚方式
  sevenPunishMoney: number = 0; //行政处罚金额
  sevenMoneyLoss: string = ""; //造成经济损失
  sevenRecordDate: string = ""; //立案日期
  sevenFolderNumber: string = ""; //案卷号
  sevenFolderUser: string = ""; //立卷人
  sevenCaseUser: string = ""; //案件办理人
  sevenCloseCaseDate: string = ""; //结案日期
  sevenCaseParty: string = ""; //案件当事人
  sevenCaseOrigin: string = ""; //案由
  sevenStoragePeriod: string = ""; //保管期限
  sevenPoliceIsAgree: string = ""; //公安机关同意立案
  eightRedeemLoss: string = ""; //挽回经济损失
  eightHandlingUser: string = ""; //经办人
  eightHandlingTime: string = ""; //经办时间
  eightJudgementFile: string = ""; //判决书
  eightResult: string = ""; //处理结果
  eightSitePhoto: string = ""; //现场照片
  eightCaseResult: string = ""; //案件处理结果
  nineHandleTime: string = ""; //处理时间
  nineHandleSituation: string = ""; //处理情况
  disposeTime: string = ""; //处置时间
  disposeResult: string = ""; //处置结果
  instanceId: string = ""; //流程实例id
  source: number = 0; //来源
  status: number = 0; //状态
  description: string = ""; //描述
  endTime: string = ""; //归档时间
  submitOrg: string = "";
  phone: string = "";
  voltageLevel: number = 0;
  new: boolean = false;
}
